CREATE DATABASE IF NOT EXISTS db_absensi_perpus
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE db_absensi_perpus;

CREATE TABLE IF NOT EXISTS mahasiswa (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nim VARCHAR(30) NOT NULL UNIQUE,
    nama VARCHAR(120) NOT NULL,
    prodi VARCHAR(120) NOT NULL,
    jenjang VARCHAR(10) NOT NULL,
    alamat VARCHAR(255) NOT NULL,
    semester TINYINT UNSIGNED NOT NULL,
    tahun_akademik VARCHAR(20) NOT NULL,
    rfid_uid VARCHAR(64) NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS guest (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    guest_id VARCHAR(20) NOT NULL UNIQUE,
    nama VARCHAR(120) NOT NULL,
    alamat VARCHAR(255) NOT NULL,
    asal_kampus VARCHAR(120) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS absensi (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tipe ENUM('mahasiswa', 'guest') NOT NULL,
    ref_id VARCHAR(30) NOT NULL,
    tanggal DATE NOT NULL,
    jam TIME NOT NULL,
    tahun_akademik VARCHAR(20) NULL,
    semester TINYINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_absensi_tanggal (tanggal),
    INDEX idx_absensi_tipe (tipe),
    INDEX idx_absensi_ref_id (ref_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS admin (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(60) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nama VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
